### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/galata#14]
We should publish `galata` to `npm`, so it can easily be added as a dependency in other projects, list the galata example:

https://github.com/jupyterlab/galata/blob/1bae0284a599ead4f64ed1fe87ae5f12efdade07/packages/galata-example/package.json#L12

Things to check before releasing:

- Release strategy: how often and when (depending on the JupyterLab release cycle?)
- Versioning
- API breaking changes

**Comment by blink1073** [comment]
Initial release: https://www.npmjs.com/package/@jupyterlab/galata

**Comment by jtpio** [comment]
Great!

**Comment by jtpio** [comment]
Closing as fixed.
