### ISSUE TITLE
Rendering artifacts lead to false positive

### ISSUE THREAD

**Issue by maartenbreddels** [jupyterlab/galata#32]
## Description

I'm seeing false positives, described at https://github.com/spacetelescope/jdaviz/pull/543#issuecomment-823301319 . The capture of the output cells seems ok, but it seems to be capturing a part of the Jupyter Lab 3.0 interface (with different portions grey each time). I'm not sure this is a user bug or a Galata bug.

**Comment by mbektas** [comment]
@maartenbreddels this is a bit surprising, cell output captures should have recorded only the output area. Can you try these:
- Can you make sure reference images are generated by GitHub Actions as described [here](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/dev_testing.md#reference-image-captures)?
- I checked the notebook tested, it seems to create an Application as cell output. Is it creating widget UI asynchronously in multiple steps? Is the cell output rendered after a noticeable wait? Are there multiple resizes happening before cell output is fully rendered? In that case adding a wait after cell execution could help. As the first line of [`onAfterCellRun`](https://github.com/spacetelescope/jdaviz/pull/543/files#diff-10e442ae09b17472dc9f937d03a0ab9b68ccbb2c1c6ca5b07a76ff36643476bcR115) function, you can try adding `await galata.waitFor(2000);` for example. 
- Can I test this notebook in binder or similar web location?

**Comment by mbektas** [comment]
@maartenbreddels Galata had several updates since you reported this issue and recently the project was merged into JupyterLab core repository with this PR https://github.com/jupyterlab/jupyterlab/pull/10796. Please test again with the latest Galata package and create an issue in https://github.com/jupyterlab/jupyterlab if problem persists.
