### ISSUE TITLE
More robust way to move items to the left area

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/galata#47]
A more robust fix could be to retrieve all the items programmatically instead of manually overriding them with `overrides["id"] = "left"; `

_Originally posted by @jtpio in https://github.com/jupyterlab/galata/issues/45#issuecomment-856941640_

**Comment by fcollonval** [comment]
Naive question, but do we really want to move all items in the left sidebar. This looks like a bad idea as some extensions are set to open by default in the right sidebar. So we will miss the case where the default position was unintentionally changed.

**Comment by jtpio** [comment]
> Naive question, but do we really want to move all items in the left sidebar. This looks like a bad idea as some extensions are set to open by default in the right sidebar. So we will miss the case where the default position was unintentionally changed.

Probably the original intent was to reset the UI in a predictable way, and maybe one of the selectors depends on the items being in the left area?

I agree it would be nice to make this more generic and robust, also related to https://github.com/jupyterlab/galata/issues/46 when folks will want to use `galata` for third-party extensions.
