### ISSUE TITLE
Improve Image Diff viewer in result report

### ISSUE THREAD

**Issue by mbektas** [jupyterlab/galata#65]
Support for `side-by-side view`, `swipe` and `transition` like GitHub PR image diff would be great

**Comment by jtpio** [comment]
With https://github.com/jupyterlab/jupyterlab/pull/10796 and https://github.com/jupyterlab/galata/issues/81 Galata is now producing a Playwright HTML report directly.

@mbektas Would you like to report this issue as a feature request on the upstream Playwright repo?

**Comment by fcollonval** [comment]
A candidate for that could be: https://www.npmjs.com/package/react-image-diff

**Comment by mbektas** [comment]
thanks @jtpio and @fcollonval, let me research how Playwright reports work and we can consider an enhancement built into that. I will close this issue for now.

**Comment by fcollonval** [comment]
FYI 
The html report web page of Playwright are defined there: https://github.com/microsoft/playwright/tree/master/src/web/htmlReport
The HTML `Reporter` is defined there: https://github.com/microsoft/playwright/blob/master/src/test/reporters/html.ts
